### ISSUE TITLE
Fundmentals of Data Structures

### ISSUE THREAD

**Issue by RAGHAVS1304** [aman-chhetri/Data-Structures-and-Algorithms#1]
# Fundmentals of Data Structures
- Linked list
- Stacks
- Binary Trees
## i will be providing my coding notes for these topics .

**Comment by RAGHAVS1304** [comment]
@aman-chhetri please assign this issue to me.
Thanks

**Comment by GauraviVeling** [comment]
Hello . Please can you assign this this issue to me . I can provide notes on linked lists , stack , queues and trees.

**Comment by aman-chhetri** [comment]
@RAGHAVS1304 @GauraviVeling The issued have been assigned! You can carry on now

**Comment by RAGHAVS1304** [comment]
@aman-chhetri Sir i have raised the PR please review it 
Thanks.
